### ISSUE TITLE
Pages needs to refreshed to update state on liking or unliking the post 

### ISSUE THREAD

**Issue by itsnitinr** [itsnitinr/driwwwle-old#1]
Currently, when a user wants to like or unlike a post, the post page has to be refreshed for the changes to be reflected. This is mostly due to improper state management. The relevant files would be PostHeader.component.jsx and PostPage.component.jsx which can be found in `client/src/components/post-header` and `client/src/pages/post-page` respectively.

**Comment by harshguptahg007** [comment]
I would like to work on this

**Comment by itsnitinr** [comment]
@harshguptahg007 I would be really glad to have you work on this. I'll be sure to update the issue with more details in some time.

**Comment by itsnitinr** [comment]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/34748469/94666611-4de0fe80-032b-11eb-9f93-a75bce054355.gif)
Here's a demo of this issue. You can replicate this issue by going to [Driwwwle Website](https://driwwwle.herokuapp.com/), creating an account, and trying to like or unlike a post.

**Comment by harshguptahg007** [comment]
Please assignee this to me. I will fix this issue.

**Comment by harshguptahg007** [comment]
How do i run the APIs in the dev environment? I think the project is missing the base url for the APIs

**Comment by itsnitinr** [comment]
@harshguptahg007 To run the backend code, you can use the `npm run dev` command in the project's root folder which will start the Express server as well as the React server. API calls are made to localhost:5000/endpoint in the development environment. All API endpoints are available in `routes/api` folder. I hope I was able to clarify,

**Comment by harshguptahg007** [comment]
@itsnitinr i am getting status code 431, which means Request Header Fields too large, when hitting the simple api for sign up even. Am I missing something here? I installed the dependencies as per the documentation

**Comment by itsnitinr** [comment]
@harshguptahg007 That's unusual. How are you trying to hit the endpoints? Postman? Can you please attach a screenshot of the error and the process you're using to hit the endpoints? The Content-Type header should be set to `application/json` in Postman.

**Comment by harshguptahg007** [comment]
I was hitting it on the dev version of the website, in the browser only.
[
![Screenshot from 2020-09-30 16-37-51](https://user-images.githubusercontent.com/30952367/94678180-b932cc80-033b-11eb-94bb-4706b8d16f5d.png)
](url)

Is the backend code on dev running fine? Cause i am getting a log that the application is crashing, after the line server started on port 5000.

**Comment by itsnitinr** [comment]
@harshguptahg007 Tested the backend code on local server just now. Have you filled the default.json file in config folder? 
![Screenshot_20200930_164426](https://user-images.githubusercontent.com/34748469/94678616-69083a00-033c-11eb-8e84-f5c88a30b923.png)

**Comment by harshguptahg007** [comment]
I have filled the default.json file with random values,

**Comment by itsnitinr** [comment]
The MONGO_URI value needs to be a valid address. Do you have MongoDB installed on your system? If yes, you can change the MONGO_URI value to `mongodb://localhost:27017/driwwwle`. Hope that helps.
