### ISSUE TITLE
Sign in button gets stuck in loading state even if the credentials are wrong

### ISSUE THREAD

**Issue by itsnitinr** [itsnitinr/driwwwle-old#11]
In the sign-in page, when a user presses on the sign-in button, a request to the backend is made during which the 'is-loading' Bulma CSS class gets added to the button which adds a spinner to the button and makes it disabled. For a successful sign-in request, this works great but if the user enters the wrong credentials, the button gets stuck on loading phase and stays disabled until the page is refreshed. 

**Steps to reproduce:**
1. Create an account and log out.
2. Try to sign in but enter wrong password.
3. Button doesn't revert back to initial state and stays on loading state.

**Component responsibile**: [Sign In Component](https://github.com/itsnitinr/driwwwle/blob/master/client/src/pages/signin-page/SigninPage.component.jsx)

Demo: 
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/34748469/94787656-36b81480-03f0-11eb-9081-b6e300033299.gif)

**Comment by MaximeKoitsalu** [comment]
Hey @itsnitinr I can look into it :)

**Comment by itsnitinr** [comment]
Great! @MaximeKoitsalu I will assign it to you and thank you so much for helping.

**Comment by MaximeKoitsalu** [comment]
@itsnitinr Created a pull request with fixes. Saw you were using setIsSubmitting in three components so added the fix to all three :)
