### ISSUE TITLE
Loader/Spinner With Submit Button in the Sign-In page never stops after getting an error.

### ISSUE THREAD

**Issue by nijin26** [itsnitinr/driwwwle-old#16]
I came to notice that, in the sign-in page, if we click submit button the loader starts and never stops even though there is an error in the entered details & shows an error message.

That is if a user encounter wrong password/email error message then they can't access the submit button.

In the Redux code, you have made the loading state to false if login fails and indeed you have done the conditional checking on the Submit button. Even though, loading spinner never stops

**Comment by itsnitinr** [comment]
Hi @nijin26. Thanks for reporting. #12 fixes this issue. I've also pushed the changes to live website on Heroku. Please check it out :)
