### ISSUE TITLE
Restrict only images to be uploaded instead of all file types using multer and multer-cloudinary-storage

### ISSUE THREAD

**Issue by itsnitinr** [itsnitinr/driwwwle-old#2]
[Driwwwle](https://driwwwle.herokuapp.com/) has a feature of adding images to each post. Currently, the user can upload any type of file but I want only the image file types to be accepted. The relevant backend code is present in [this file](https://github.com/itsnitinr/driwwwle/blob/master/middleware/cloudinary.js). I am using multer and multer-storage-cloudinary packages for image upload purposes. 

Backend route for creating a new post including the image: [Here](https://github.com/itsnitinr/driwwwle/blob/master/routes/api/posts.js)

Frontend React component for new post: [Here](https://github.com/itsnitinr/driwwwle/blob/master/client/src/pages/add-post-page/AddPostPage.component.jsx)

![Screenshot_20200930_145136](https://user-images.githubusercontent.com/34748469/94667484-7fa69500-032c-11eb-8971-5af78782d738.png)

**Comment by anatdagan** [comment]
Hi Nitin,
Please assign this issue to me.
Thanks, Anat
