### ISSUE TITLE
Footer position changes based on the page's content

### ISSUE THREAD

**Issue by shahednasser** [itsnitinr/driwwwle-old#4]
The position of the footer isn't always at the bottom of the page. It shifts based on the amount of content on the page.

This can be fixed by setting a `min-height` on `#root > .container` but I suggest giving the container a more specific id or class name.

**Comment by itsnitinr** [comment]
@shahednasser Thank you once again for finding this issue. Would you like me to assign this to you? Really appreciate your inputs.

**Comment by shahednasser** [comment]
@itsnitinr yes assign me
